name: titulacion_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  animated_text_kit: ^4.2.3
  cloud_firestore: ^5.6.5
  dio: ^5.8.0+1
  email_validator: ^3.0.0
  file_picker: ^9.0.2
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_pdfview: ^1.4.0
  flutter_svg: ^2.0.17
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  provider: ^6.1.2
  universal_html: ^2.2.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/vectors/
    - assets/educacion.png
    - assets/mujer.png
    - assets/indigena.png
    - assets/ar.png
    - assets/ar14.png
    - assets/plastico.png
    - assets/itz.png
    - assets/laboral.png
